services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer-compose
    # ports:
    #  - 9443:9443
    #  - 8000:8000
    volumes:
        - ./portainer_data:/data
        #- data:/data
        #- /var/run/docker.sock:/var/run/docker.sock 
        - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.rule=Host(`portainer.hobozzzx.live`)
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    networks:
      - traefik-network
networks:
  traefik-network:
    external: true